{"name": "test_valid_login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed\nassert 'Logged In Successfully' == 'Logged In Su...fully!!!!!!!!'\n  \n  - Logged In Successfully!!!!!!!!\n  ?                       --------\n  + Logged In Successfully", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ffa4946be8d7dec53f5ca36703b95e20\")>\n\n    @allure.feature(\"Login Tests\")\n    @pytest.mark.positive\n    def test_valid_login(driver):\n        login_page = LoginPage(driver)\n        login_page.login(VALID_USERNAME, VALID_PASSWORD)\n        assert login_page.get_current_url() == \"https://practicetestautomation.com/logged-in-successfully/\", \"Invalid redirection\"\n    \n        home_page = HomePage(driver)\n>       assert home_page.get_success_message() ==SUCCESS_LOGIN_MESSAGE, \"Login failed\"\nE       AssertionError: Login failed\nE       assert 'Logged In Successfully' == 'Logged In Su...fully!!!!!!!!'\nE         \nE         - Logged In Successfully!!!!!!!!\nE         ?                       --------\nE         + Logged In Successfully\n\ntests\\test_login.py:17: AssertionError"}, "start": 1741294002819, "stop": 1741294003893, "uuid": "c3bc1b98-724b-453b-8172-cee53f668237", "historyId": "ab68c09e23714aa68c720c2ca07c0ecf", "testCaseId": "ab68c09e23714aa68c720c2ca07c0ecf", "fullName": "tests.test_login#test_valid_login", "labels": [{"name": "feature", "value": "Login Tests"}, {"name": "tag", "value": "positive"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "MyPC"}, {"name": "thread", "value": "2248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}