{"name": "test_invalid_login[incorrectUser-Password123-Incorrect login]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nassert 'Your username is invalid!' == 'Incorrect login'\n  \n  - Incorrect login\n  + Your username is invalid!", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f15c3aecfdcc9ddcf99aa77639a62106\")>\nlogin_elements = (<selenium.webdriver.remote.webelement.WebElement (session=\"f15c3aecfdcc9ddcf99aa77639a62106\", element=\"f.BA067D0D035D...c3aecfdcc9ddcf99aa77639a62106\", element=\"f.BA067D0D035DD77190FD1E9980C7C21F.d.18C4FEE62E38ACD8B5AA0CC42A2D72AE.e.15\")>)\nusername_input = 'incorrectUser', password_input = 'Password123'\nexpected_message = 'Incorrect login'\n\n    @pytest.mark.negative\n    @pytest.mark.parametrize(\"username_input, password_input, expected_message\", [\n        (\"incorrectUser\", \"Password123\", \"Incorrect login\"),  # Test incorrect username\n        (\"student\", \"123\", \"Your password is invalid!\"),     # Test incorrect password\n        (\"incorrectUser\", \"123\", \"Your username is invalid!\")  # Test both incorrect\n    ])\n    def test_invalid_login(driver, login_elements, username_input, password_input, expected_message):\n        username, password, submit = login_elements\n        username.send_keys(username_input)\n        password.send_keys(password_input)\n        submit.click()\n    \n        pop_up = WebDriverWait(driver, 5).until(\n            EC.visibility_of_element_located((By.XPATH, '/html/body/div[1]/div/section/section/div[2]'))\n        )\n        pop_up_message = pop_up.text\n>       assert pop_up_message == expected_message, f\"Expected '{expected_message}', but got '{pop_up_message}'\"\nE       AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nE       assert 'Your username is invalid!' == 'Incorrect login'\nE         \nE         - Incorrect login\nE         + Your username is invalid!\n\nlogin_page.py:72: AssertionError"}, "parameters": [{"name": "username_input", "value": "'incorrectUser'"}, {"name": "password_input", "value": "'Password123'"}, {"name": "expected_message", "value": "'Incorrect login'"}], "start": 1740143575022, "stop": 1740143575267, "uuid": "fd709ffd-3126-4027-bd8d-a362709ae5e8", "historyId": "3896d7a44dd642a9c2b0119d1f4b3723", "testCaseId": "6674ddf48017f312a808400bc8fd64ec", "fullName": "login_page#test_invalid_login", "labels": [{"name": "tag", "value": "negative"}, {"name": "suite", "value": "login_page"}, {"name": "host", "value": "MyPC"}, {"name": "thread", "value": "17500-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_page"}]}