{"name": "test_invalid_login[incorrectUser-Password123-Incorrect login]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nassert 'Your username is invalid!' == 'Incorrect login'\n  \n  - Incorrect login\n  + Your username is invalid!", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f4fe560b77f8b03915565b11300f7dc4\")>\nlogin_elements = (<selenium.webdriver.remote.webelement.WebElement (session=\"f4fe560b77f8b03915565b11300f7dc4\", element=\"f.02FAB5F5324F...e560b77f8b03915565b11300f7dc4\", element=\"f.02FAB5F5324FBB8055D4240555C119F8.d.B6744453848EEFD7F7A3E60EE58B524D.e.29\")>)\nusername_input = 'incorrectUser', password_input = 'Password123', expected_message = 'Incorrect login'\n\n    @pytest.mark.negative\n    @pytest.mark.parametrize(\"username_input, password_input, expected_message\", [\n        (\"incorrectUser\", \"Password123\", \"Incorrect login\"),  # Test incorrect username\n        (\"student\", \"123\", \"Your password is invalid!\"),     # Test incorrect password\n        (\"incorrectUser\", \"123\", \"Your username is invalid!\")  # Test both incorrect\n    ])\n    def test_invalid_login(driver, login_elements, username_input, password_input, expected_message):\n        username, password, submit = login_elements\n        username.send_keys(username_input)\n        password.send_keys(password_input)\n        submit.click()\n    \n        pop_up = WebDriverWait(driver, 5).until(\n            EC.visibility_of_element_located((By.XPATH, '/html/body/div[1]/div/section/section/div[2]'))\n        )\n        pop_up_message = pop_up.text\n>       assert pop_up_message == expected_message, f\"Expected '{expected_message}', but got '{pop_up_message}'\"\nE       AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nE       assert 'Your username is invalid!' == 'Incorrect login'\nE         \nE         - Incorrect login\nE         + Your username is invalid!\n\nlogin_page.py:72: AssertionError"}, "parameters": [{"name": "username_input", "value": "'incorrectUser'"}, {"name": "password_input", "value": "'Password123'"}, {"name": "expected_message", "value": "'Incorrect login'"}], "start": 1740146216471, "stop": 1740146217261, "uuid": "d2ac6fd9-424c-4d8f-aa0b-3a481f0c1d33", "historyId": "3896d7a44dd642a9c2b0119d1f4b3723", "testCaseId": "6674ddf48017f312a808400bc8fd64ec", "fullName": "login_page#test_invalid_login", "labels": [{"name": "tag", "value": "negative"}, {"name": "suite", "value": "login_page"}, {"name": "host", "value": "MyPC"}, {"name": "thread", "value": "2320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_page"}]}