{"name": "test_invalid_login[incorrectUser-Password123-Incorrect login]", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nassert 'Your username is invalid!' == 'Incorrect login'\n  \n  - Incorrect login\n  + Your username is invalid!", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"76320bfed904d0697aa9720150041da5\")>\nlogin_elements = (<selenium.webdriver.remote.webelement.WebElement (session=\"76320bfed904d0697aa9720150041da5\", element=\"f.139AE40C101C...20bfed904d0697aa9720150041da5\", element=\"f.139AE40C101CF02EE18C4847A7C78B0E.d.BEBA81C3CFEC46082F9A8BD70486C17B.e.29\")>)\nusername_input = 'incorrectUser', password_input = 'Password123', expected_message = 'Incorrect login'\n\n    @pytest.mark.negative\n    @pytest.mark.parametrize(\"username_input, password_input, expected_message\", [\n        (\"incorrectUser\", \"Password123\", \"Incorrect login\"),  # Test incorrect username\n        (\"student\", \"123\", \"Your password is invalid!\"),     # Test incorrect password\n        (\"incorrectUser\", \"123\", \"Your username is invalid!\")  # Test both incorrect\n    ])\n    def test_invalid_login(driver, login_elements, username_input, password_input, expected_message):\n        username, password, submit = login_elements\n        username.send_keys(username_input)\n        password.send_keys(password_input)\n        submit.click()\n    \n        pop_up = WebDriverWait(driver, 5).until(\n            EC.visibility_of_element_located((By.XPATH, '/html/body/div[1]/div/section/section/div[2]'))\n        )\n        pop_up_message = pop_up.text\n>       assert pop_up_message == expected_message, f\"Expected '{expected_message}', but got '{pop_up_message}'\"\nE       AssertionError: Expected 'Incorrect login', but got 'Your username is invalid!'\nE       assert 'Your username is invalid!' == 'Incorrect login'\nE         \nE         - Incorrect login\nE         + Your username is invalid!\n\nlogin_page.py:72: AssertionError"}, "parameters": [{"name": "username_input", "value": "'incorrectUser'"}, {"name": "password_input", "value": "'Password123'"}, {"name": "expected_message", "value": "'Incorrect login'"}], "start": 1740147483251, "stop": 1740147483548, "uuid": "ff00fee1-0db3-4258-a850-fddcc7d0f93f", "historyId": "3896d7a44dd642a9c2b0119d1f4b3723", "testCaseId": "6674ddf48017f312a808400bc8fd64ec", "fullName": "login_page#test_invalid_login", "labels": [{"name": "tag", "value": "negative"}, {"name": "suite", "value": "login_page"}, {"name": "host", "value": "MyPC"}, {"name": "thread", "value": "7384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "login_page"}]}